import { createElement } from "lwc";
import Lc_hooks from "c/lc_hooks";

describe("c-lc-hooks", () => {
	afterEach(() => {
		// The jsdom instance is shared across test cases in a single file so reset the DOM
		while (document.body.firstChild) {
			document.body.removeChild(document.body.firstChild);
		}
	});

	it("TODO: test case generated by CLI command, please fill in test logic", () => {
		// Arrange
		const element = createElement("c-lc-hooks", {
			is: Lc_hooks
		});

		// Act
		document.body.appendChild(element);

		// Assert
		// const div = element.shadowRoot.querySelector('div');
		expect(1).toBe(1);
	});
});
